#- name: Apply common installation and config
#  hosts: slurm_control_node, slurm_node, login
#  gather_facts: false
#  any_errors_fatal: true
#  roles:
#    - { role: omnia/scheduler/common }

- name: Apply common Slurm installation and config
  hosts: slurm_control_node, slurm_node, login
  gather_facts: false
  roles:
    - { role: omnia.scheduler.slurm.slurm_common }

- name: Apply slurm control node config
  hosts: slurm_control_node
  gather_facts: false
  roles:
    - { role: omnia.scheduler.slurm.slurm_manager }

- name: Configure Slurm worker nodes
  hosts: slurm_node, login
  gather_facts: false
  roles:
    - { role: omnia.scheduler.slurm.slurm_workers }

- name: Start slurm services on slurm control node
  hosts: slurm_control_node
  gather_facts: false
  roles:
    - { role: omnia.scheduler.slurm.slurm_start_services }

- name: Start slurm services on slurm node and login
  hosts: slurm_node, login
  gather_facts: false
  roles:
    - { role: omnia.scheduler.slurm.slurm_workers_service }
